// lib/core/theme/theme_parts/color_schemes.dart

import 'package:flutter/material.dart';
import 'package:receiptsly/core/theme/app_colors.dart';

class ColorSchemes {
  static const ColorScheme lightColorScheme = ColorScheme.light(
    primary: AppColors.primary,
    onPrimary: AppColors.white,
    primaryContainer: AppColors.primaryExtraLight,
    onPrimaryContainer: AppColors.primaryExtraDark,
    secondary: AppColors.secondary,
    onSecondary: AppColors.white,
    secondaryContainer: AppColors.secondaryExtraLight,
    onSecondaryContainer: AppColors.secondaryExtraDark,
    tertiary: AppColors.accent,
    onTertiary: AppColors.white,
    tertiaryContainer: AppColors.accentLight,
    onTertiaryContainer: AppColors.accentDark,
    error: AppColors.error,
    onError: AppColors.white,
    errorContainer: AppColors.errorExtraLight,
    onErrorContainer: AppColors.errorDark,
    background: AppColors.lightBackground,
    onBackground: AppColors.lightTextPrimary,
    surface: AppColors.lightSurface,
    onSurface: AppColors.lightTextPrimary,
    surfaceVariant: AppColors.lightSurfaceVariant,
    onSurfaceVariant: AppColors.lightTextSecondary,
    outline: AppColors.lightBorder,
    outlineVariant: AppColors.lightBorderLight,
    shadow: AppColors.shadowLight,
    scrim: AppColors.overlay,
    inverseSurface: AppColors.darkSurface,
    onInverseSurface: AppColors.darkTextPrimary,
    inversePrimary: AppColors.primaryLight,
  );

  static const ColorScheme darkColorScheme = ColorScheme.dark(
    primary: AppColors.primaryLight,
    onPrimary: AppColors.black,
    primaryContainer: AppColors.primaryDark,
    onPrimaryContainer: AppColors.primaryExtraLight,
    secondary: AppColors.secondaryLight,
    onSecondary: AppColors.black,
    secondaryContainer: AppColors.secondaryDark,
    onSecondaryContainer: AppColors.secondaryExtraLight,
    tertiary: AppColors.accentLight,
    onTertiary: AppColors.black,
    tertiaryContainer: AppColors.accentDark,
    onTertiaryContainer: AppColors.accentLight,
    error: AppColors.errorLight,
    onError: AppColors.black,
    errorContainer: AppColors.errorDark,
    onErrorContainer: AppColors.errorLight,
    background: AppColors.darkBackground,
    onBackground: AppColors.darkTextPrimary,
    surface: AppColors.darkSurface,
    onSurface: AppColors.darkTextPrimary,
    surfaceVariant: AppColors.darkSurfaceVariant,
    onSurfaceVariant: AppColors.darkTextSecondary,
    outline: AppColors.darkBorder,
    outlineVariant: AppColors.darkBorderLight,
    shadow: AppColors.shadowDarkLight,
    scrim: AppColors.overlay,
    inverseSurface: AppColors.lightSurface,
    onInverseSurface: AppColors.lightTextPrimary,
    inversePrimary: AppColors.primary,
  );
}
